require_relative 'types/array_type'
require_relative 'types/fixed_length_string_type'
require_relative 'types/function_pointer_type'
require_relative 'types/null_terminated_string_type'
require_relative 'types/pointer_type'
require_relative 'types/simple_type'
